#!/bin/bash -xe

abort() {
    echo >&2 "
*** ABORTED ***
: ${1}
"
    exit 1
}

RELEASE_TAG=${RELEASE_TAG:=release-test-0-02}
RELEASE_VERSION=${RELEASE_VERSION:=0.02}
DEV_VERSION=${DEV_VERSION:=0.03-CURBSIDE-SNAPSHOT}

# -- assertions (env/etc) --
[[ -n "${ARTIFACTORY_USER}" ]] || abort "missing ARTIFACTORY_USER"
[[ -n "${ARTIFACTORY_PASS}" ]] || abort "missing ARTIFACTORY_PASS"

# -- Remove all possible leftovers related to previous release --
mvn release:clean

# -- Ensure that the code is building properly before tagging it for release --
mvn clean install -DskipTests

# -- prepare the release --
mvn --settings core/files/settings.xml --batch-mode -Dtag=${RELEASE_TAG} -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${DEV_VERSION} -DpreparationGoals=clean release:prepare

# -- do the release --
mvn --settings core/files/settings.xml  release:perform  -Darguments="-DskipTests" -Pweb-bundle
